### ISSUE TITLE
"file" not defined if configparser is unable to parse file

### ISSUE THREAD

**Issue by freegroup** [ZachPerkitny/configparser#5]
In the line https://github.com/ZachPerkitny/configparser/blob/master/src/configparser.js#L265 and https://github.com/ZachPerkitny/configparser/blob/master/src/configparser.js#L258 you are reference the attribute file. The var is not defined and ends in exception if a parser error happens.

```
(node:8) UnhandledPromiseRejectionWarning: ReferenceError: file is not defined
    at /app/node_modules/configparser/src/configparser.js:263:45
    at Array.forEach (<anonymous>)
    at ConfigParser.parseLines (/app/node_modules/configparser/src/configparser.js:248:11)
    at ConfigParser.read (/app/node_modules/configparser/src/configparser.js:109:16)
    at Startup (/app/src/index.js:12:10)
    at Object.<anonymous> (/app/src/index.js:254:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

```

**Comment by ZachPerkitny** [comment]
Thanks for reporting the issue, I just fixed it and released 0.3.7.
